// Code generated by MockGen. DO NOT EDIT.
// Source: request/pokeapi/interface.go

// Package mock_request_pokeapi is a generated GoMock package.
package mock_request_pokeapi

import (
	reflect "reflect"

	custom_error "github.com/alvinwijaya/pokemon-battle-royale/custom_error"
	pokeapi "github.com/alvinwijaya/pokemon-battle-royale/model/pokeapi"
	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// GetAllInPagination mocks base method.
func (m *MockInterface) GetAllInPagination() (*pokeapi.PokeapiPaginationResponseDTO, *custom_error.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInPagination")
	ret0, _ := ret[0].(*pokeapi.PokeapiPaginationResponseDTO)
	ret1, _ := ret[1].(*custom_error.ServiceError)
	return ret0, ret1
}

// GetAllInPagination indicates an expected call of GetAllInPagination.
func (mr *MockInterfaceMockRecorder) GetAllInPagination() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInPagination", reflect.TypeOf((*MockInterface)(nil).GetAllInPagination))
}

// GetByID mocks base method.
func (m *MockInterface) GetByID(id uint64) (*pokeapi.PokeapiGetByIDResponseDTO, *custom_error.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*pokeapi.PokeapiGetByIDResponseDTO)
	ret1, _ := ret[1].(*custom_error.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInterfaceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInterface)(nil).GetByID), id)
}
